# Generated by Django 3.2.9 on 2022-02-27 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=210)),
        ),
    ]
