# Generated by Django 3.2.9 on 2022-02-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_music_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='author',
        ),
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ManyToManyField(related_name='tracks', to='base.Author'),
        ),
    ]
