# Generated by Django 3.2.9 on 2022-02-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220227_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='listened',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
